modLoader="javafml" #mandatory
loaderVersion="[33,37)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="DSMSL (DON'T SNATCH MA STUFF LICENSE)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="spiffyhud" #mandatory
version="1.5.0" #mandatory
displayName="Spiffy HUD" #mandatory
authors="Keksuccino" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/spiffy-hud-forge" #optional
description='''The spiffiest HUD in the hood!

COPYRIGHT:

> Spiffy HUD © Copyright 2021-2022 Keksuccino.
  Spiffy HUD is licensed under DSMSL (DON'T SNATCH MA STUFF LICENSE).
  See https://github.com/Keksuccino/Spiffy-HUD/blob/main/LICENSE.md for more information about this license.'''

[[dependencies.spiffyhud]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.3.3,)"
side="BOTH"

[[dependencies.spiffyhud]]
modId="fancymenu"
mandatory=false
ordering="AFTER"
versionRange="[2.5.2,)"
side="BOTH"

[[dependencies.spiffyhud]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="CLIENT"

[[dependencies.spiffyhud]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"
ordering="NONE"
side="CLIENT"