modLoader="javafml" #mandatory
loaderVersion="[33,37)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="KML (Keksuccino Mod License)"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="fancyhud" #mandatory
version="1.3.0" #mandatory
displayName="FancyHud" #mandatory
authors="Keksuccino" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/fancyhud" #optional
description='''The fanciest HUD in the hood!

COPYRIGHT:

> FancyHud © Copyright 2021 Keksuccino.
  FancyHud is licensed under KML.
  See https://github.com/Keksuccino/FancyHud/blob/main/LICENSE.md for more infos about this license.'''

[[dependencies.fancyhud]]
modId="konkrete"
mandatory=true
ordering="NONE"
versionRange="[1.1.4,)"
side="BOTH"

[[dependencies.fancyhud]]
modId="fancymenu"
mandatory=false
ordering="AFTER"
versionRange="[2.0.7,)"
side="BOTH"